### ISSUE TITLE
Unable to install applications directly in nagram x

### ISSUE THREAD

**Issue by llm2580** [risin42/NagramX#21]
![Screenshot_2024-11-26-23-52-09-65_d2b75a1e572092fe23d5ff5ef04b7792](https://github.com/user-attachments/assets/799f718f-98d7-49b2-a1a5-f243bfdbb3ae)
I don't know if this bug is nagram or telegram, I want you to see if there is a way to fix it, thanks🙏
Are there channels where you can't forward messages that can be hacked? If you can remove the restrictions, thank you very much.

**Comment by risin42** [comment]
I couldn't reproduce this issue on my end. Could you please try performing the same operation on the official version of Nagram to see if you encounter the same problem?

Nagram X has the "secure" flag disabled by default, so you should be able to directly copy or save content from restricted channels. However, the forwarding restriction is a server-side limitation and cannot be bypassed locally.

BTW, you can save messages to "saved messages", but these messages won't be synced to the cloud, and the server will know that you are doing something inappropriate. I suggest you refrain from doing so.
